// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Actor struct {
	ID        int64
	ActorID   pgtype.UUID
	Name      string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Category struct {
	ID         int64
	CategoryID pgtype.UUID
	Category   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Channel struct {
	ID          int64
	ChannelID   pgtype.UUID
	Name        string
	Description pgtype.Text
	Pic         pgtype.Text
	Banner      pgtype.Text
	OwnedBy     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Comment struct {
	ID            int64
	CommentID     pgtype.UUID
	VideoID       int64
	Comment       string
	CommentedBy   int64
	Likes         pgtype.Int8
	ParentComment pgtype.Int8
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Subtitle struct {
	ID         int64
	SubtitleID pgtype.UUID
	Language   string
	FilePath   string
	BelongTo   int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Tag struct {
	ID        int64
	TagID     pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        int64
	UserID    pgtype.UUID
	Username  string
	Email     string
	Password  string
	Active    pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type Video struct {
	ID            int64
	VideoID       pgtype.UUID
	Name          string
	Description   pgtype.Text
	Source        string
	Poster        string
	PostedBy      int64
	VideoMetadata int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type VideoActor struct {
	VideoID   int64
	ActorID   int64
	CreatedAt pgtype.Timestamptz
}

type VideoCategory struct {
	VideoID    int64
	CategoryID int64
	CreatedAt  pgtype.Timestamptz
}

type VideoMetadatum struct {
	ID              int64
	VideoMetadataID pgtype.UUID
	Likes           pgtype.Int8
	Views           pgtype.Int8
	Shares          pgtype.Int8
	Comments        pgtype.Int8
	PostedAt        pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type VideoTag struct {
	VideoID int64
	TagID   int64
}
